# syntax=docker/dockerfile:1

FROM golang:1.22 AS build
WORKDIR /src
COPY . .
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build -o /out/app ./cmd/{{ .Name }}

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=build /out/app /app/{{ .Name }}
ENV APP_ENV=production
EXPOSE 8080
ENTRYPOINT ["/app/{{ .Name }}"]
