SVC={{ .Name }}

.PHONY: run build tidy
run:
	go run ./cmd/$(SVC)

build:
	go build -o bin/$(SVC) ./cmd/$(SVC)

tidy:
	go mod tidy

# Generate gRPC code (requires protoc + plugins):
#   go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
#   go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
#   brew install protobuf   # or apt/yum equivalent
proto:
	protoc -I . \
	  api/helloworld/v1/greeter.proto \
	  --go_out=. --go_opt=paths=source_relative \
	  --go-grpc_out=. --go-grpc_opt=paths=source_relative